### ISSUE TITLE
Modlist is not listed on wabbajack 

### ISSUE THREAD

**Issue by StevelandCleaner** [ArnoldDP/OStim-Community-Modlist#1]
Hi, 

As title suggests, unless I am being blind I cannot see this modlist listed in the wabbajack gallery. 

Has it been taken down?

**Comment by darnedgenie** [comment]
I also cant find it on the modlist, but I think you can download the mods if you follow the load order that's posted (that's to much work for me at the moment) I think that is the intended use with this modlist but I'm not sure.
